### ISSUE TITLE
vim_ai_complete_default and vim_ai_edit_default model can't be changed

### ISSUE THREAD

**Issue by eadadi** [madox2/vim-ai#105]
When changing the model of either vim_ai_complete_default or vim_ai_edit_default to another one (e.g. gpt-4o) then they stop working,
and an error suggesting that API key should be verified is logged.

**Comment by Konfekt** [comment]
Maybe you ran into https://github.com/madox2/vim-ai/commit/ccf981974232636d08a48094bf9dad3812a43cc8#comments as well and have to set "endpoint_url" explicitly?

**Comment by Konfekt** [comment]
What model is `gpt-4o`? Maybe you could try with more common ones first, say `gpt-4-turbo`

**Comment by eadadi** [comment]
It's the one they released recently, but gpt-4-turbo does not work for me as well

**Comment by Konfekt** [comment]
Are you sure the API key is correct? That's been usually the cause of these 400 error messages if I recall correctly.

**Comment by eadadi** [comment]
Yes I do, use vim-ai a lot- just wanted to upgrade to the new model.

**Comment by Konfekt** [comment]
Maybe setting `g:vim_ai_debug = 1` will reveal more than a mere `400` error.

**Comment by pedrohgmacedo** [comment]
The [completions api](https://platform.openai.com/docs/api-reference/completions/create) uses a different format for the request than chat, and it does not support models later than gpt 3.5

**Comment by eadadi** [comment]
Interesting, I have seen that the 3.5-turbo-instruction called so (...-instruction) only for legacy reason, and it is not truly optimized for instruction, so seemingly we could profit from adjusting to the other models.

Maybe I will look further to suggest how to support it

**Comment by pedrohgmacedo** [comment]
Ideally, I think the plugin should be decoupled from the openai api format, and endpoint would be plugged using adapters.

**Comment by madox2** [comment]
`gpt-4o ` model can be used only with chat engine (api `/v1/chat/completions`), you can configure chat engine also for [completions and edits](https://github.com/madox2/vim-ai?tab=readme-ov-file#using-chat-engine-for-completion-and-edits). Since `/v1/completions` is now considered a legacy, it could make sense to use chat engine for completions by default.

@pedrohgmacedo I like the idea of adapters, but since there are no big differences between API/model providers, I find it simpler to stick to [OpenAI-compatible APIs](https://github.com/madox2/vim-ai?tab=readme-ov-file#using-custom-api) as there are many tools/services providing such compatibility layer.

**Comment by pedrohgmacedo** [comment]
> @pedrohgmacedo I like the idea of adapters, but since there are no big differences between API/model providers, I find it simpler to stick to [OpenAI-compatible APIs](https://github.com/madox2/vim-ai?tab=readme-ov-file#using-custom-api) as there are many tools/services providing such compatibility layer.

Some providers are icky and don't offer a compatible api, for instance google gemini or cohere. I'm currently hosting my own adapter on cloudflare, instead of forking the plugin.

**Comment by madox2** [comment]
There are tools like [litellm](https://github.com/BerriAI/litellm) that expose openai-compatible proxy to most of the llm providers. But like you said, you need to host it yourself or run locally
