### ISSUE TITLE
:AIE makes the line just disappear

### ISSUE THREAD

**Issue by clime** [madox2/vim-ai#20]
![scr1](https://user-images.githubusercontent.com/2030528/232625978-8cb47820-5783-47c2-bade-fa734a449432.png)
![scr2](https://user-images.githubusercontent.com/2030528/232626001-445efd89-0bbc-4ceb-98b9-9b4a6fe65565.png)

I have tried AIE command to make the variables `username` and `password` and use them in the `conn` statement but the target line just disappears with no error given. (I have verified the plugin works on other commands before).

If at that position I do `'<,'>AIE make variables`. it wil actually start producing some lines.

**Comment by clime** [comment]
Also `:'<,'>AI introduce username and password variables` when the line is selected just inserts a new line and nothing is generated (without any error).

**Comment by madox2** [comment]
Hi, thanks for pointing this out! The thing is that sometimes openai API responds with an empty message. I don't know the reason but I guess it is because of how the model works and how the prompt is constructed.

Sometime it helps to try different prompts, e.g. I got a completion in your example with the prompt:

```
:'<,'>AIE replace username and password with variables
```

Often helps to put more context into prompt e.g. a programming language:

```
:'<,'>AIE in rust, replace username and password with variables
```

I don't see an empty response as an error necessarily, but I agree it would be nice to let user know that the response is empty. I will add an message for that.

**Comment by madox2** [comment]
This is interesting. The way I construct the prompt for `:AI`, `:AIE` is:

```
instruction:
visual selection
```

Which translates to:

```
make variables username and password and use them in the conn statement:
let conn = Connection::connect("postgresql://username:password@localhost:5432/dbname", TlsMode::None).unwrap();
```

However when I surround visual selection with `###` (can't remember where I saw this trick), it seems to give more likely non empty response:

```
make variables username and password and use them in the conn statement:
###
let conn = Connection::connect("postgresql://username:password@localhost:5432/dbname", TlsMode::None).unwrap();
###
```

I need to experiment with that a little bit, but if it works it could be a great improvement.

**Comment by clime** [comment]
I rather wonder, why the response is empty (error messsage/warning would certainly help) and what I can do to prevent that from happening :).

That being said `:'<,'>AIE replace username and password with variables` does do the correct thing :).

Btw. another improvement that would be great (yet a small thing) would be if the indentation of the edited block was maintained :).

Btw. this plugin is really quite nice.

**Comment by madox2** [comment]
Some warning message with a suggestion what to do sounds good.

I agree, code indentation would be nice. In the beginning I had it implemented, but decided to disable it because if the response is more than a code (e.g. some commentary what often happens), then it could really ugly mess up the indentation. But let me figure it out

**Comment by madox2** [comment]
Anyway, if you want to join me on testing the idea with `###` block, you can install the plugin from the `empty-response-elimination` branch

**Comment by clime** [comment]
Sure!

**Comment by clime** [comment]
I can confirm it fixed the original problem I had :). The original long prompt now, indeed, produces:

```
let username = "myusername";
let password = "mypassword";

let conn = Connection::connect("postgresql://myusername:mypassword@localhost:5432/dbname", TlsMode::None).unwrap();
```

**Comment by cutalion** [comment]
I can confirm it fixed the problem for me too.

I asked `:AIEdit sort by population` on visual selection of cities.

Example:
```
List of capitals:
1. London
2. Toronto
3. Boston
4. Miami
5. Honolulu
```

**Comment by madox2** [comment]
Thank you guys for the testing! The trick worked pretty well for me too with `text-davinci-003` model. Little bit worse with `gpt-3.5-turbo`, it use to output the `#####` in the response, but anyway this model outputs empty responses less likely.

Long story short: I made it configurable with `options.selection_boundary` property.
